### ISSUE TITLE
add traffic rules and fines

### ISSUE THREAD

**Issue by AnmolChalaune** [RiyaRanaChhetrii/E-Challan-System#7]
traffic rules breakage and their respective fines add in the CRUD

**Comment by aarav124** [comment]
I have addded all the above mentioned fields.

**Comment by aarav124** [comment]
I have addded all the above mentioned fields.

**Comment by aarav124** [comment]
![15](https://user-images.githubusercontent.com/89212464/162785285-76a3a215-3d7b-42cf-a6c9-9607e8e55032.PNG)
